project:
  type: website
  output-dir: docs

website:
  title: "Neuron Consulting"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    toc: true