project:
  type: website
  output-dir: docs

website:
  title: "Neuron Consulting"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - left_side.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: slate
    css: styles.css
    toc: true